name = "vepronix"
license = "MIT"
licenselink = "https://github.com/veprogames/vepronix/blob/main/LICENSE"
description = "A very simple, high contrast (AMOLED) theme."
homepage = "https://github.com/veprogames/vepronix"
tags = []
features = []
min_version = "0.112.3"

[author]
  name = "vepro"
  homepage = "https://veprogames.github.io"