name = "vepronix"

# TBD
#license = "MIT"
#licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"

description = "A very simple, high contrast (AMOLED) theme."
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.112.3"

[author]
  name = "vepro"
  homepage = "https://veprogames.github.io"